### ISSUE TITLE
Missing Date Header entry

### ISSUE THREAD

**Issue by joshin42** [gguillen/galeranotify#5]
I submitted a pull request to fix errors I was seeing on regarding the "Date" field missing in the header of notification messages. It manifested on my mail server in two ways:
1) Thunderbird would assign the date the messages were grabbed by the client as the send date
2) Amavis would flag messages with: "X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date""

**Comment by gguillen** [comment]
Fixed in v1.4.  Thank you.

**Comment by joshin42** [comment]
Glad to help. Thank you for creating it!
