### ISSUE TITLE
Date is not RFC-compliant

### ISSUE THREAD

**Issue by jsmad** [gguillen/galeranotify#6]
Hello,

The date field is not RFC 2822 compliant, thus it causes emails to fail spam validation, for example spamassassin raises spam score by marking them with "INVALID_DATE". In addition, some email clients fail to parse the date and thus the email is lost at the bottom of the list, instead of being sorted by date.

I'm using the following format, which is RFC compliant and solved the above problems:

```python
DATE = datetime.datetime.now().strftime( "%a, %d %b %Y %H:%M:%S %z" )
```

**Comment by ofrias** [comment]
It also works with:

`DATE = email.utils.formatdate()`

**Comment by gguillen** [comment]
Thanks for bringing this up @jsmad and thanks to @ofrias for the final solution.
