### ISSUE TITLE
Set 'wsrep_notify_cmd = ' in your my.cnf file.

### ISSUE THREAD

**Issue by thaylin** [gguillen/galeranotify#7]
What is the proper syntax for this, just 'python /$pathto/galeranotify.py'?

**Comment by gguillen** [comment]
Grant execute permission to the mysql user (or whatever user your mysql is running as).  Then usage should be:

wsrep_notify_cmd = /probablyusr/probablybin/galeranotify.py

Full documentation is available on the Galera site: [http://galeracluster.com/documentation-webpages/notificationcmd.html](http://galeracluster.com/documentation-webpages/notificationcmd.html)
